export const USER_TYPES = {
  LOGIN_REQ: 'LOGIN_REQUEST',
  LOGIN_SUC: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FALIURE',
  LOGOUT_REQ: 'LOGIN_REQUEST',
  LOGOUT_SUC: 'LOGOUT_REQUEST',
  LOGOUT_FAIL: 'LOGOUT_FALIURE',
  VERIFY_REQUEST: 'VERIFY_REQUEST',
  VERIFY_SUCCESS: 'VERIFY_SUCCESS',
};
